### ISSUE TITLE
The Hack Has Stopped Working As Of Now 11/24/2020

### ISSUE THREAD

**Issue by NeoHex-Codex** [Elspex/skidfest#1]
The hack has stopped working, it alerts things such as "Failed to Find Inputs", "Failed to Find isHacker", "Failed to Find respawnT", "Failed to Find recoilY", Failed to find objInstances",  and finally "Failed to find reloadTimer". The skins don't show up anymore, the game gets slow and buggy, there is no more esp or aimbot. Only the menu opens but it becomes useless due to those errors. 

Questions:
--------------
Does changing the billboard text change it on other people computer?
Can the skins you select be seen by other players?

That's it, thx in advance.

**Comment by Alextreme09** [comment]
That is the same problem that happens to me, do you know any solution or any other script? ):

**Comment by JASFramework** [comment]
The hack has stopped working, it alerts things such as "Failed to Find Inputs", "Failed to Find isHacker", "Failed to Find respawnT", "Failed to Find recoilY", Failed to find objInstances", and finally "Failed to find reloadTimer". The skins don't show up anymore, the game gets slow and buggy, there is no more esp or aimbot. Only the menu opens but it becomes useless due to those errors.
_________________________________

Hi, I have used this hack for a while and it did this a lot from the beginning. All I had to do was turn the hack on, type in Krunker.io then switch tabs while it loaded in. That stopped the popups. 

Sadly the hack no longer works as you have said.

**Comment by JASFramework** [comment]
The hack has stopped working, it alerts things such as "Failed to Find Inputs", "Failed to Find isHacker", "Failed to Find respawnT", "Failed to Find recoilY", Failed to find objInstances", and finally "Failed to find reloadTimer". The skins don't show up anymore, the game gets slow and buggy, there is no more esp or aimbot. Only the menu opens but it becomes useless due to those errors.
_________________________________

Hi, I have used this hack for a while and it did this a lot from the beginning. All I had to do was turn the hack on, type in Krunker.io then switch tabs while it loaded in. That stopped the popups. 

Sadly the hack no longer works as you have said.

**Comment by Elspex** [comment]
The hack is under maintenance right now. It will be back in a few days!
